[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/",
]

[fmt]
ignore = []

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
 
[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
